### ISSUE TITLE
Ready for review

### ISSUE THREAD

**Issue by jfallgit** [HKSTechDevelopment/front-end-repo#25]
**Webpage:** https://hkstechdevelopment.github.io/front-end-repo/

**Front end repository:** https://github.com/HKSTechDevelopment/front-end-repo

**Back end repository:** https://github.com/HKSTechDevelopment/back-end-repo

**Trello:** https://trello.com/b/Y8RRtoVq/teamdevelopment-task-board

**Comment by dmil** [comment]
Thanks! Project has been reviewed and feedback has been sent to you via email! I'm closing this github issue.
